#!/bin/bash

set -e

# APP_DIR is defined in Dockerfile

################################################################################
# start nginx in background
if [ -d "${APP_DIR}/nginx-conf.d" ]; then
  echo ">>>> starting nginx proxy ..."
  cp $APP_DIR/nginx-conf.d/*.conf /etc/nginx/conf.d
  nginx -g 'daemon off;' &
else
  echo ">>>> no nginx config configured in ${APP_DIR}/nginx-conf.d, nginx proxy skipped."
fi
echo

################################################################################
# import environment .env
if [ -f "${APP_DIR}/.env" ]; then
  echo ">>>> importing .env ..."
  export $(grep -v '^#' "${APP_DIR}/.env" | xargs)
else
  echo ">>>> no .env environment variables to import."
fi
echo ">>>> current environment variables:"
env
echo

################################################################################
# start application
if [[ $# -gt 0 ]]; then
  echo ">>>> starting command line ..."
  exec "$@"
elif [ -f "${APP_DIR}/bootstrap.sh" ]; then
  echo ">>>> starting application (bootstrap.sh) ..."
  chmod a+x "${APP_DIR}/bootstrap.sh"
  exec "${APP_DIR}/bootstrap.sh"
else
  echo ">>>> starting bash (default action) ..."
  exec "/bin/bash"
fi
